# Generated by Django 2.2.28 on 2023-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cder',
            name='eswer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
